manifest: 
  group-filter: [-infr]
  
  defaults:
      remote: github-xmos

  remotes:
    - name: github-xmos
      url-base: git@github.com:xmos
    - name: github-int
      url-base: git@github0.xmos.com:xmos-int

  self: 
      path: sw_usb_audio

  projects: 
    - name: lib_xua
      revision: v3.3.1

    - name: lib_dsp
      revision: v6.2.1

    - name: lib_i2c
      revision: v6.1.1

    - name: lib_i2s
      revision: v5.0.0

    - name: lib_locks
      revision: v2.1.0
    
    - name: lib_logging
      revision: v3.1.1
    
    - name: lib_mic_array
      revision: v4.5.0
    
    - name: lib_spdif
      revision: v4.2.1
  
    - name: lib_xassert
      revision: v4.1.0

    - name: lib_xud
      revision: v2.2.1

    - name: lib_adat
      revision: v1.0.1

    - name: tools_released
      groups: [infr]
      remote: github-int
      revision: v15.1.4

