all : html

SPHINX_PROJECT_NAME=XMOS USB Audio Interface Software Design Guide
VERSION=1.0
APPS_ROOT=../../..
DOXYGEN_DIRS=$(APPS_ROOT)/sc_usb_audio $(APPS_ROOT)/sc_xud
SOURCE_INCLUDE_DIRS=$(APPS_ROOT)/sw_usb_aud_l1_ios
XDOC_DIR ?= $(APPS_ROOT)/xdoc
BREADCRUMB_PREFIX=<li><a href="../../index.html">Home</a></li>
XDEDOC_TITLE_PREFIX=XMOS USB Audio Interface
include $(XDOC_DIR)/Makefile.inc
