all : xmospdf xmoshtml

DOXYGEN_DIRS=../../sc_xud ../../sc_spdif ../../sc_adat ../../lib_xua
SOURCE_INCLUDE_DIRS=../../sw_usb_audio ../../lib_xua
XDOC_DIR ?= ../../../xdoc
BREADCRUMB_PREFIX=<li><a href="../../index.html">Home</a></li>
include $(XDOC_DIR)/Makefile.inc
REVISION=6.1
