#define DEBUG_PRINT_ENABLE_COPRO_DEBUG          1

#define DEBUG_PRINT_ENABLE_IAP_DEBUG            1
#define DEBUG_PRINT_ENABLE_IAP1_DEBUG           1
#define DEBUG_PRINT_ENABLE_IAP2_LINK_DEBUG      1
#define DEBUG_PRINT_ENABLE_IAP2_CTRL_SESS_DEBUG 1
