#define DEBUG_PRINT_ENABLE_COPRO_DEBUG          0

#define DEBUG_PRINT_ENABLE_IAP_DEBUG            0
#define DEBUG_PRINT_ENABLE_IAP1_DEBUG           0
#define DEBUG_PRINT_ENABLE_IAP2_LINK_DEBUG      0
#define DEBUG_PRINT_ENABLE_IAP2_CTRL_SESS_DEBUG 0
